# Generated by Django 4.0.10 on 2023-08-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(max_length=65, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=65, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.почта')),
                ('password', models.CharField(max_length=65, verbose_name='Пароль')),
            ],
        ),
    ]
