# Generated by Django 4.0.10 on 2023-08-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='БИО')),
            ],
            options={
                'verbose_name': 'Фотограф',
                'verbose_name_plural': 'Фотографы',
                'ordering': ['users'],
            },
        ),
    ]
