# Generated by Django 4.0.10 on 2023-08-09 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photographer',
            options={'ordering': ['users'], 'verbose_name': 'Фотограф', 'verbose_name_plural': 'Фотографы'},
        ),
    ]
