# Generated by Django 4.0.10 on 2023-08-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.CharField(choices=[('WOODEN', 'Деревянные'), ('GLASS', 'Стеклянные'), ('METAL', 'Металлические'), ('CERAMIC', 'Керамические'), ('PLUSH', 'Плюшевые')], default='WOODEN', max_length=25, verbose_name='Рамки')),
                ('size', models.CharField(choices=[('ONE', '9х13 см'), ('TWO', '9х13 см'), ('THREE', '15х20 см'), ('FOUR', '20х30 см')], default='ONE', max_length=25, verbose_name='Размеры')),
                ('price', models.FloatField(verbose_name='цена')),
            ],
            options={
                'verbose_name': 'рамка',
                'verbose_name_plural': 'рамки',
            },
        ),
    ]
