# Generated by Django 4.0.10 on 2023-08-09 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photographers', '0002_alter_photographer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='цена')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='photographers.photographer')),
            ],
            options={
                'verbose_name': 'рамка',
                'verbose_name_plural': 'рамки',
            },
        ),
    ]
