# Generated by Django 4.0.10 on 2023-08-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='frame',
            field=models.CharField(choices=[('WOODEN', 'Деревянные'), ('GLASS', 'Стеклянные'), ('METAL', 'Металлические'), ('CERAMIC', 'Керамические'), ('PLUSH', 'Плюшевые')], default='WOODEN', max_length=25, verbose_name='Рамки'),
        ),
        migrations.AddField(
            model_name='frame',
            name='size',
            field=models.CharField(choices=[('ONE', '9х13 см'), ('TWO', '9х13 см'), ('THREE', '15х20 см'), ('FOUR', '20х30 см')], default='ONE', max_length=25, verbose_name='Размеры'),
        ),
    ]
